routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', function () {
    return redirect('/admin');
});

Route::group(['prefix' => 'admin'], function () {
    App::setLocale('vi');
    Auth::routes();
});

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin', 'name' => 'admin.'],
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');


        //user
        Route::get('user/data', 'UserController@data')->name('user.data');
        Route::resource('user', 'UserController');
        //category
        Route::get('category/data', 'CategoryController@data')->name('category.data');
        Route::resource('category', 'CategoryController');
        //product
        Route::get('product/data', 'ProductController@data')->name('product.data');
        Route::resource('product', 'ProductController');
        //post
        Route::get('post/data', 'PostController@data')->name('post.data');
        Route::resource('post', 'PostController');
    });

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $collection = 'categories';

    protected $fillable = ['name','slug','description'];

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Intervention\Image\ImageManagerStatic as Image;

class CategoryController extends Controller
{
    public function data(Request $request)
    {
        if (empty($request->input('start'))) {
            $request->request->add([
                'start' => '0'
            ]);
        }
        if (empty($request->input('length')) || $request->input('length') === '-1') {
            $request->request->add([
                'length' => Category::all()->count()
            ]);
        }
        if (empty($request->input('search.value'))) {
            $request->request->add([
                'search' => [
                    'value' => '',
                    'regex' => 'false'
                ]
            ]);
        }
        $query = DB::table('categories')
                ->leftJoin('cate_type','cate_type.id','=','categories.type')
                ->select('categories.*','cate_type.name as type_name');
        if ($request->input('search.value')) {
            $query->where('categories.name', 'like', '%' . $request->input('search.value') . '%');
        }
        $data = $query->orderBy($request->input('columns.' . $request->input('order.0.column') . '.data') ? $request->input('columns.' . $request->input('order.0.column') . '.data') : 'id', $request->input('order.0.dir') === 'asc' ? 'asc' : 'desc')
            ->skip(intval($request->input('start')))
            ->take(intval($request->input('length')))
            ->get()
            ->toArray();
        $result = [
            'draw' => intval($request->input('draw', 1)),
            'recordsTotal' => intval(Category::all()->count()),
            'recordsFiltered' => intval($query->count()),
            'data' => empty($data) ? [] : $data
        ];
        die(json_encode($result));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Admin.Category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type = DB::table('cate_type')
                ->select('cate_type.*')
                ->get();
        return view('Admin.Category.create',compact('type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:191',
            'type' => 'required',
        ]);
        $cate               = new Category();
        $cate->name         = $request->name;
        $cate->description  = $request->description;
        $cate->type         = $request->type;
        $cate->slug         = str_slug($request->name);
        if($request->img_path){
            $cate->img_name     = $request->img_path;
            $cate->img_path     = 'assets/uploads/' . $request->img_path;
        }
        $cate->save();
        return redirect()->route('category.index')->with('message', __('messages.category') . ' ' . __('messages.created') . ' ' . __('messages.successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $type = DB::table('cate_type')->select('cate_type.*')->get();
        return view('Admin.Category.edit',compact('type','category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required',
            'type' => 'required',
        ]);
        $category->name = $request->name;
        $category->description = $request->description;
        $category->slug = str_slug($request->name);
        $category->type = $request->type;
        if($request->img_path){
            $category->img_name     = $request->img_path;
            $category->img_path     = 'assets/uploads/' . $request->img_path;
        }
        $category->update();
        return redirect()->route('category.index')->with('message',__('messages.category').' '.__('messages.update').' '.__('messages.successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('category.index')->with('message', __('messages.category') . ' ' . __('messages.deleted') . ' ' . __('messages.successfully'));
    }
}

resources/views/Admin/Category/create.blade.php
@extends('layouts.backend')
@section('content')
<style>
    img {
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        width: 100%;
    }

    img:hover {
        box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
    }
</style>
<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.category') }}</h1>
    </div>
    <!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
            <li class="breadcrumb-item active">{{ __('messages.category') }} </li>
        </ol>
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
</div><!-- /.container-fluid -->
</div>
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h5><i class="icon fas fa-ban"></i>
        @foreach ($errors->all() as $error)
        {{ $error }}
        @endforeach
    </h5>
</div>
@endif
<form method="post" action="{{ route('category.store') }}" enctype="multipart/form-data">
    <div class="row">
        <!-- left column -->
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.add_new') }} {{ __('messages.category') }}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">{{ __('messages.cate_name') }}</label>
                        <abbr title="required">*</abbr>
                        <input type="text" class="form-control" id="name" name="name" onkeyup="ChangeToSlug();" placeholder="{{ __('messages.cate_name') }}">
                    </div>
                    <div class="form-group">
                        <label for="description">{{ __('messages.description') }}</label>
                        <textarea type="text" class="form-control" name="description" id="description" placeholder="{{ __('messages.description') }}"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="type">{{ __('messages.type') }}</label>
                        <abbr title="required">*</abbr><br>
                        @foreach($type as $item)
                        <input type="radio" id="type" name="type" value="{{$item->id}}">
                        <label for="type">{{$item->name}}</label>&#160;&#160;&#160;&#160;
                        @endforeach
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                    <button type="reset" class="btn btn-success"><i class="fas fa-redo-alt"></i> Reset</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:window.location='{{ route('category.index') }}';"><i class="fas fa-sign-out-alt"></i> Cancel</button>
                </div>
            </div>
            <!-- /.card -->
        </div>
        <div class="col-md-4">
            <!-- general form elements disabled -->
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.static_path') }}</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <label>{{ __('messages.slug') }}</label>
                        <input type="text" class="form-control" id="slug" name="slug" placeholder="{{ __('messages.slug') }}" disabled="">
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <div class="card card-light">
                <!-- /.card-header -->
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.avatar') }}</h3>
                </div>
                <!-- /.card-body -->
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
                <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
                <div class="card-body">
                    <div class="row">
                        <label for="img_path">{{ __('messages.avatar') }}</label>
                        <div class="input-group">
                            <input type="text" name="img_path" id="image-input" class="form-control" readonly>
                            <span class="input-group-append">
                                    <button href="{{ asset('/assets/filemanager/dialog.php?relative_url=1&type=1&field_id=image-input') }}"
                                            name="img_path"  type="button" id="avatar" class="btn  btn-primary iframe-btn" >{{ __('messages.upload_avatar') }}</button>
                                </span>
                        </div>
                    </div><br>
                    <div class="row">
                        <img id="avatar_img" class="image-preview" onClick="swipe();"  width="100%" height="50%" border="1px">
                    </div>
                </div>
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</form>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#avatar_img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#avatar").change(function() {
        readURL(this);
    });
</script>
<script type="text/javascript">
    $("document").ready(function(){
        setTimeout(function(){
            $("div.alert").remove();
        }, 2000 ); // 2 secs

    });
</script>
{{--config select avatar--}}
<script type="text/javascript">
    $('.iframe-btn').fancybox({
        'type'		: 'iframe',
        'autoScale'    	: false,

    });
    function swipe() {
        var largeImage = document.getElementById('avatar_img');
        var url=largeImage.getAttribute('src');
        window.open(url,'Image','width=largeImage.stylewidth,height=largeImage.style.height,resizable=1');
    }
    function responsive_filemanager_callback(field_id){
        console.log(field_id);
        var url=jQuery('#'+field_id).val();
        $('.image-preview').attr('src','{{ asset('/assets/uploads/') }}' +'/'+ url);
    }
</script>
@endsection

resources/views/Admin/Category/edit.blade.php
@extends('layouts.backend')
@section('content')
    <style>
        img {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 5px;
            width: 100%;
        }
        img:hover {
            box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
        }
        .fancybox-slide--iframe .fancybox-content {
            width  : 800px;
            height : 600px;
            max-width  : 80%;
            max-height : 80%;
            margin: 0;
        }
    </style>
<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{ __('messages.edit') }} {{ __('messages.category') }}</h1>
    </div>
    <!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
            <li class="breadcrumb-item active">{{ __('messages.category') }} </li>
        </ol>
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
</div><!-- /.container-fluid -->
</div>
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h5><i class="icon fas fa-ban"></i>
        @foreach ($errors->all() as $error)
        {{ $error }}
        @endforeach
    </h5>
</div>
@endif
<form method="post" action="{{ route('category.update',$category->id) }}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <!-- left column -->
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.edit') }} {{ __('messages.category') }}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">{{ __('messages.cate_name') }}</label>
                        <abbr title="required">*</abbr>
                        <input type="text" class="form-control" id="name" name="name" onkeyup="ChangeToSlug();" placeholder="{{ __('messages.cate_name') }}" value={{$category->name}}>
                    </div>
                    <div class="form-group">
                        <label for="description">{{ __('messages.description') }}</label>
                        <textarea type="text" class="form-control" name="description" id="description" placeholder="{{ __('messages.description') }}">{{$category->description}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="type">{{ __('messages.type') }}</label>
                        <abbr title="required">*</abbr><br>
                        @foreach($type as $item)
                        <input type="radio" id="type" name="type" value="{{$item->id}}" @if($category->type == $item->id) checked @endif>
                        <label for="type">{{$item->name}}</label>&#160;&#160;&#160;&#160;
                        @endforeach
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                    <button type="reset" class="btn btn-success"><i class="fas fa-redo-alt"></i> Reset</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:window.location='{{ route('category.index') }}';"><i class="fas fa-sign-out-alt"></i> Cancel</button>
                </div>
            </div>
            <!-- /.card -->
        </div>
        <div class="col-md-4">
            <!-- general form elements disabled -->
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.static_path') }}</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <label>{{ __('messages.slug') }}</label>
                        <input type="text" class="form-control" id="slug" name="slug" value="{{ $category->slug }}" placeholder="Enter ..." disabled="">
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <div class="card card-light">
                <!-- /.card-header -->
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.avatar') }}</h3>
                </div>
                <!-- /.card-body -->
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
                <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
                <div class="card-body">
                    <div class="row">
                        <label for="avatar">{{ __('messages.avatar') }}</label>
                        <div class="input-group">
                            <input type="text" name="img_path" placeholder="{{ $category->img_name }}"
                                   value="{{ $category->img_name }}" id="image-input" class="form-control" readonly>
                            <span class="input-group-append">
                                <button href="{{ asset('/assets/filemanager/dialog.php?relative_url=1&type=1&field_id=image-input') }}" name="img_path"  type="button" id="avatar" class="btn  btn-primary iframe-btn" >{{ __('messages.upload_avatar') }}</button>
                            </span>
                        </div>
                    </div><br>
                    <div class="row">
                        @if($category->img_path == null)
                            <em>{{ __('messages.avatar_null') }}</em>
                        @else
                            <div class="custom-control custom-switch custom-switch-off-danger custom-switch-on-success">
                                <input type="checkbox" class="custom-control-input" id="customSwitch3" name="delete_avatar" >
                                <label class="custom-control-label" for="customSwitch3">{{ __('messages.delete_avatar') }}</label>
                            </div>
                            <img class="image-preview" onclick="swipe()" src="{{ asset($category->img_path) }}" id="avatar_img" width="100%" height="50%" border="1px">
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</form>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#avatar_img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#avatar").change(function() {
        readURL(this);
    });
</script>
<script type="text/javascript">
    $("document").ready(function(){
        setTimeout(function(){
            $("div.alert").remove();
        }, 2000 ); // 2 secs

    });
</script>
<script type="text/javascript">
    function responsive_filemanager_callback(field_id){
        var url=jQuery('#'+field_id).val();
        $('.image-preview').attr('src','{{ asset('/assets/uploads/') }}' +'/'+ url);
    }
</script>
<script type="text/javascript">
    $('.iframe-btn').fancybox({
        'type'		: 'iframe',
        'autoScale'    	: false
    });
    function swipe() {
        var largeImage = document.getElementById('avatar_img');
        var url=largeImage.getAttribute('src');
        window.open(url,'Image','width=largeImage.stylewidth,height=largeImage.style.height,resizable=1');
    }
</script>
@endsection

resources/views/Admin/Category/index.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.category') }}</h1>
        </div>
        <!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('messages.category') }} </li>
            </ol>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
    </div>
    <div class="row">
        <div class="col-12">
            @if (session()->has('message'))
                <div class="alert alert-success" id="alert">
                    {{ session()->get('message') }}
                </div>
            @endif
            <!-- /.card -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.category') }}</h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a href="{{ route('category.create') }}" class="btn bg-gradient-info btn-sm">
                                    <i class="fas fa-plus"></i>&nbsp;{{ __('messages.add_new') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <table id="table" class="table table-bordered table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('messages.no.') }}</th>
                            <th>{{ __('messages.cate_name') }}</th>
                            <th>{{ __('messages.category') }}</th>
                            <th>{{ __('messages.avatar') }}</th>
                            <th>{{ __('messages.view') }}</th>
                            <th>{{ __('messages.edit') }}</th>
                            <th>{{ __('messages.delete') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- page script -->
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{{ route('category.data') }}",
                "columns": [{
                    "data": null
                },
                    {
                        "data": "name",
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("category.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '">' + data + '</a>';
                        }
                    },
                    {
                        "data": "type_name",
                    },
                    {
                        "data":"img_path",
                        "render": function(data,type,row,meta){
                            if(data == null){
                                return '<em>{{ __('messages.avatar_null') }}</em>';
                            }
                            else {
                                return '<img class="border border-secondary" src="{{ asset('/') }}' + data +'" width="30" height="30">';
                            }
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("category.show",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '" title="{{ __('messages.view') }}"><img src="{{ asset('img/view.svg') }}" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("category.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '" title="{{ __('messages.edit') }}"><img src="{{ asset('img/edit.svg') }}" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("category.destroy",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<form action="' + url + '" method="post">@csrf @method('DELETE')<button type="submit" class="btn p-0 border-0 bg-transparent" onclick="return confirm(' + "'{{ __('messages.delete_confirmation') }}'" + ')" title="{{ __('messages.delete') }}"><img src="{{ asset('img/delete.svg') }}" width="30" height="30"></button></form>';
                        }
                    }
                ],
                "lengthMenu": [
                    [10, 25, 50, 100, -1],
                    [10, 25, 50, 100, "{{ __('messages.all') }}"]
                ],
                "pagingType": "full_numbers",
                "responsive": {
                    "details": false
                },
                "columnDefs": [{
                    "orderable": false,
                    "targets": [0,3,4,5,6]
                },
                    {
                        "responsivePriority": 1,
                        "targets": [1,2,3,5]
                    },
                    {
                        "className": "text-center",
                        "targets": [0,2,3,4,5,6]
                    }
                ],
                "order": [
                    [1, 'asc']
                ],
                "language": {
                    "processing": "{{ __('messages.processing') }}...",
                    "info": "{{ __('messages.showing') }} _START_ {{ __('messages.to') }} _END_ {{ __('messages.of') }} _TOTAL_ {{ __('messages.entries') }}",
                    "infoEmpty": "{{ __('messages.infoEmpty') }}",
                    "infoFiltered": "({{ __('messages.filtered') }} {{ __('messages.from') }} _MAX_ {{ __('messages.total') }} {{ __('messages.entries') }})",
                    "lengthMenu": "{{ __('messages.show') }} _MENU_ {{ __('messages.entries') }}",
                    "paginate": {
                        "first": "«",
                        "last": "»",
                        "next": "›",
                        "previous": "‹"
                    },
                    "search": "{{ __('messages.search') }}:",
                    "emptyTable": "{{ __('messages.emptyTable') }}",
                    "zeroRecords": "{{ __('messages.zeroRecords') }}"
                }
            });
            table.on('draw.dt', function() {
                var info = table.page.info();
                table.column(0, {
                    search: 'applied',
                    order: 'applied',
                    page: 'applied'
                }).nodes().each(function(cell, i) {
                    cell.innerHTML = i + 1 + info.start;
                });
            });
        });
    </script>
    <script type="text/javascript">
        $("document").ready(function(){
            setTimeout(function(){
                $("div.alert").remove();
            }, 2000 ); // 2 secs

        });
    </script>
@endsection