routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', function () {
    return redirect('/admin');
});

Route::group(['prefix' => 'admin'], function () {
    App::setLocale('vi');
    Auth::routes();
});

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin', 'name' => 'admin.'],
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');


        //user
        Route::get('user/data', 'UserController@data')->name('user.data');
        Route::resource('user', 'UserController');
        //category
        Route::get('category/data', 'CategoryController@data')->name('category.data');
        Route::resource('category', 'CategoryController');
        //product
        Route::get('product/data', 'ProductController@data')->name('product.data');
        Route::resource('product', 'ProductController');
        //post
        Route::get('post/data', 'PostController@data')->name('post.data');
        Route::resource('post', 'PostController');
    });

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $collection = 'posts';

    protected $fillable = ['title','metaTitle','slug','content','published','img_name','img_path'];

    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:m:s',
        'updated_at' => 'datetime:Y-m-d H:m:s',
    ];
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class PostController extends Controller
{
    public function data(Request $request)
    {
        if (empty($request->input('start'))) {
            $request->request->add([
                'start' => '0'
            ]);
        }
        if (empty($request->input('length')) || $request->input('length') === '-1') {
            $request->request->add([
                'length' => Post::all()->count()
            ]);
        }
        if (empty($request->input('search.value'))) {
            $request->request->add([
                'search' => [
                    'value' => '',
                    'regex' => 'false'
                ]
            ]);
        }
        $query = Post::query();
        if ($request->input('search.value')) {
            $query->where('title', 'like', '%' . $request->input('search.value') . '%');
        }
        $data = $query->orderBy($request->input('columns.' . $request->input('order.0.column') . '.data') ? $request->input('columns.' . $request->input('order.0.column') . '.data') : 'id', $request->input('order.0.dir') === 'asc' ? 'asc' : 'desc')
            ->skip(intval($request->input('start')))
            ->take(intval($request->input('length')))
            ->get()
            ->toArray();
        $result = [
            'draw' => intval($request->input('draw', 1)),
            'recordsTotal' => intval(Post::all()->count()),
            'recordsFiltered' => intval($query->count()),
            'data' => empty($data) ? [] : $data
        ];
        die(json_encode($result));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Admin.Post.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = DB::table('categories')->leftJoin('cate_type','categories.type','cate_type.id')
            ->where('cate_type.name','Category')->select('categories.id','categories.name')->get();
        $tag = DB::table('categories')->leftJoin('cate_type','categories.type','cate_type.id')
            ->where('cate_type.name','Tag')->select('categories.id','categories.name')->get();
        return view('Admin.Post.create',compact('category','tag'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new Post();
        $post->title        = $request->title;
        $post->metaTitle    = $request->meta_title;
        $post->slug         = $request->title;
        $post->content      = $request->content;
        if ($request->published != 'on'){
            $post->published    = 'off';
        }
        else{
            $post->published = $request->published;
        }
        if($request->img_path){
            $post->img_name     = $request->img_path;
            $post->img_path     = 'assets/uploads/' . $request->img_path;
        }
        $post->created_by   = Auth::user()->name;
        $post->updated_by   = Auth::user()->name;
        $post->save();
        if($request->category){
            DB::table('post_meta')->insert(array('post_id' => $post->id, 'cate_id' => $request->category));
        }
        if(is_array($request->tag) && !empty($request->tag)){
            foreach ($request->tag as $value){
                DB::table('post_meta')->insert(array('post_id' => $post->id, 'cate_id' => $value));
            }
        }
        return redirect()->route('post.index')->with('message',__('messages.post').' '.__('messages.create').' '.__('messages.successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post,Request $request)
    {
        $category = DB::table('categories')->leftJoin('cate_type','categories.type','cate_type.id')
            ->where('cate_type.name','Category')->select('categories.id','categories.name')->get();
        $tag = DB::table('categories')->leftJoin('cate_type','categories.type','cate_type.id')
            ->where('cate_type.name','Tag')->select('categories.id','categories.name')->get();
        $check_cate = DB::table('post_meta')->where('post_id', $post->id)->select('cate_id')->pluck('cate_id')->toArray();
        return view('Admin.Post.edit',compact('post','category','tag','check_cate'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        $post->title        = $request->title;
        $post->metaTitle    = $request->meta_title;
        $post->slug         = $request->title;
        $post->content      = $request->content;
        $post->published    = 'on';
        if ($request->published != 'on'){
            $post->published    = 'off';
        }
        if($request->img_path){
            $post->img_name     = $request->img_path;
            $post->img_path     = 'assets/uploads/' . $request->img_path;
        }
        $post->created_by   = Auth::user()->name;
        $post->updated_by   = Auth::user()->name;

        $post->update();
        DB::table('post_meta')
            ->leftJoin('categories','cate_id','categories.id')
            ->leftJoin('cate_type','cate_type.id','categories.id')
            ->where('post_meta.post_id',$post->id)->delete();
        if($request->category){
            DB::table('post_meta')
                ->leftJoin('categories','cate_id','categories.id')
                ->leftJoin('cate_type','cate_type.id','categories.id')
                ->where('cate_type.name', 'Category')
                ->where('post_id',$post->id)->insert(array('post_id' => $post->id, 'cate_id' => $request->category));
        }
        if(is_array($request->tag) && !empty($request->tag)){
            foreach ($request->tag as $value){
                DB::table('post_meta')
                    ->leftJoin('categories','cate_id','categories.id')
                    ->leftJoin('cate_type','cate_type.id','categories.id')
                    ->where('cate_type.name', 'Tag')->where('post_id',$post->id)
                    ->insert(array('post_id' => $post->id, 'cate_id' => $value));
            }
        }
        return redirect()->route('post.index')->with('message',__('messages.post').' '.__('messages.updated').' '.__('messages.successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        DB::table('post_meta')->where('post_id',$post->id)->delete();
        return redirect()->route('post.index')->with('message',__('messages.post').' '.__('messages.deleted').' '.__('messages.successfully'));
    }
}

resources/views/Admin/Post/create.blade.php
@extends('layouts.backend')
@section('content')
<style>
    img {
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        width: 100%;
    }
    img:hover {
        box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
    }
    .fancybox-slide--iframe .fancybox-content {
        width  : 800px;
        height : 600px;
        max-width  : 80%;
        max-height : 80%;
        margin: 0;
    }
</style>
<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.post') }}</h1>
    </div>
    <!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
            <li class="breadcrumb-item active">{{ __('messages.post') }} </li>
        </ol>
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h5><i class="icon fas fa-ban"></i>
        @foreach ($errors->all() as $error)
        {{ $error }}
        @endforeach
    </h5>
</div>
@endif
<form method="post" action="{{ route('post.store') }}" enctype="multipart/form-data">
    <div class="row">
        <!-- left column -->
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.add_new') }} {{ __('messages.post') }}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">{{ __('messages.title') }}</label>
                        <abbr title="required">*</abbr>
                        <input type="text" class="form-control" id="name" name="title" onkeyup="ChangeToSlug();" maxlength="100" placeholder="{{ __('messages.title') }}">
                        <em> {{ __('messages.note_title') }}</em>
                    </div>
                    <div class="form-group">
                        <label for="meta_title">{{ __('messages.meta_title') }}</label>
                        <abbr title="required">*</abbr>
                        <textarea type="text" class="form-control" id="meta_title" name="meta_title" onkeyup="ChangeToSlug();" maxlength="150" placeholder="{{ __('messages.meta_title') }}"></textarea>
                        <em> {{ __('messages.note_meta_title') }}</em>
                    </div>
                    <div class="form-group">
                        <label for="content">{{ __('messages.content') }}</label>
                        <textarea type="text" class="form-control" name="content" id="description" placeholder="{{ __('messages.content') }}"></textarea>
                    </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                    <button type="reset" class="btn btn-success"><i class="fas fa-redo-alt"></i> Reset</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:window.location='{{ route('post.index') }}';"><i class="fas fa-sign-out-alt"></i> Cancel</button>
                </div>
            </div>
            <!-- /.card -->
        </div>
        <div class="col-md-4">
            <!-- general form elements disabled -->
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.static_path') }}</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <label>{{ __('messages.slug') }}</label>
                        <input type="text" class="form-control" id="slug" name="slug" placeholder="{{ __('messages.slug') }}" disabled="">
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.categories') }}</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <label>{{ __('messages.category') }}</label>
                        <div class="input-group">
                            <select class="custom-select" name="category">
                                @foreach($category as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                    <div class="row">
                        <label>{{ __('messages.published') }}</label>
                        <div class="bootstrap-switch-container">
                            <span class="bootstrap-switch-label" style="width: 43.2px;">&nbsp;</span>
                            <input type="checkbox" checked="" data-bootstrap-switch="" name="published" data-off-color="danger" data-on-color="success">
                            <em> {{ __('messages.note_published') }}</em>
                        </div>
                    </div>
                    <script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
                    <div class="row">
                        <label>{{ __('messages.tag') }}</label>
                        <div class="input-group">
                            <label for="tag"></label>
                            <select id="tag" name="tag[]" multiple="multiple">
                                @foreach($tag as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><br>
                </div>
                <!-- /.card-body -->
            </div>
            <div class="card card-light">
                <!-- /.card-header -->
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.avatar') }}</h3>
                </div>
                <!-- /.card-body -->
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
                <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
                <div class="card-body">
                    <div class="row">
                        <label for="img_path">{{ __('messages.avatar') }}</label>
                        <div class="input-group">
                            <input type="text" name="img_path" id="image-input" class="form-control" readonly>
                            <span class="input-group-append">
                                    <button href="{{ asset('/assets/filemanager/dialog.php?relative_url=1&type=1&field_id=image-input') }}"
                                            name="img_path"  type="button" id="avatar" class="btn  btn-primary iframe-btn" >{{ __('messages.upload_avatar') }}</button>
                                </span>
                        </div>
                    </div><br>
                    <div class="row">
                        <img id="avatar_img" class="image-preview" onClick="swipe();"  width="100%" height="50%" border="1px">
                    </div>
                </div>
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</form>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#avatar_img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#avatar").change(function() {
        readURL(this);
    });
    $(document).ready(function() {
        $('#tag').select2({
            theme: 'bootstrap4',
        });
    });
</script>
<script type="text/javascript">
    $("document").ready(function(){
        setTimeout(function(){
            $("div.alert").remove();
        }, 2000 ); // 2 secs

    });
</script>
{{--config select avatar--}}
<script type="text/javascript">
    $('.iframe-btn').fancybox({
        'type'		: 'iframe',
        'autoScale'    	: false,

    });
    function swipe() {
        var largeImage = document.getElementById('avatar_img');
        var url=largeImage.getAttribute('src');
        window.open(url,'Image','width=largeImage.stylewidth,height=largeImage.style.height,resizable=1');
    }
    function responsive_filemanager_callback(field_id){
        console.log(field_id);
        var url=jQuery('#'+field_id).val();
        $('.image-preview').attr('src','{{ asset('/assets/uploads/') }}' +'/'+ url);
    }
    $("input[data-bootstrap-switch]").each(function(){
        $(this).bootstrapSwitch('state', $(this).prop('checked'));
    });
</script>
<script>
    // Date range
    $(function() {
        $('input[name="created_at"]').daterangepicker({
            singleDatePicker: true,
            showDropdowns: true,
            locale: {
                format: 'DD/MM/YYYY',
            }
        });
    });
</script>
@endsection

resources/views/Admin/Post/index.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.post') }}</h1>
        </div>
        <!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('messages.post') }} </li>
            </ol>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-12">
            @if (session()->has('message'))
                <div class="alert alert-success" id="alert">
                    {{ session()->get('message') }}
                </div>
            @endif
            <!-- /.card -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.post') }}</h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a href="{{ route('post.create') }}" class="btn bg-gradient-info btn-sm">
                                    <i class="fas fa-plus"></i>&nbsp;{{ __('messages.add_new') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <table id="table" class="table table-bordered table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('messages.no.') }}</th>
                            <th>{{ __('messages.title') }}</th>
                            <th>{{ __('messages.published') }}</th>
                            <th>{{ __('messages.created_by') }}</th>
                            <th>{{ __('messages.created_at') }}</th>
                            <th>{{ __('messages.view') }}</th>
                            <th>{{ __('messages.edit') }}</th>
                            <th>{{ __('messages.delete') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- page script -->
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{{ route('post.data') }}",
                "columns": [{
                    "data": null
                },
                    {
                        "data": "title",
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("post.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '">' + data + '</a>';
                        }
                    },
                    {
                        "data":"published",
                        "render": function(data,type,row,meta){
                            return '<img src="{{ asset('img/') }}' + (data != 'on' ? '/uncheck' : '/check') + '.svg" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data":"created_by",
                    },
                    {
                        "data":"created_at",
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("post.show",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '" title="{{ __('messages.view') }}"><img src="{{ asset('img/view.svg') }}" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("post.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '" title="{{ __('messages.edit') }}"><img src="{{ asset('img/edit.svg') }}" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("post.destroy",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<form action="' + url + '" method="post">@csrf @method('DELETE')<button type="submit" class="btn p-0 border-0 bg-transparent" onclick="return confirm(' + "'{{ __('messages.delete_confirmation') }}'" + ')" title="{{ __('messages.delete') }}"><img src="{{ asset('img/delete.svg') }}" width="30" height="30"></button></form>';
                        }
                    },
                ],
                "lengthMenu": [
                    [10, 25, 50, 100, -1],
                    [10, 25, 50, 100, "{{ __('messages.all') }}"]
                ],
                "pagingType": "full_numbers",
                "responsive": {
                    "details": false
                },
                "columnDefs": [{
                    "orderable": false,
                    "targets": [0,5,6,7]
                },
                    {
                        "responsivePriority": 1,
                        "targets": [1,3,5,6,7]
                    },
                    {
                        "className": "text-center",
                        "targets": [0,1,2,3,4,5,6,7]
                    }
                ],
                "order": [
                    [1, 'asc']
                ],
                "language": {
                    "processing": "{{ __('messages.processing') }}...",
                    "info": "{{ __('messages.showing') }} _START_ {{ __('messages.to') }} _END_ {{ __('messages.of') }} _TOTAL_ {{ __('messages.entries') }}",
                    "infoEmpty": "{{ __('messages.infoEmpty') }}",
                    "infoFiltered": "({{ __('messages.filtered') }} {{ __('messages.from') }} _MAX_ {{ __('messages.total') }} {{ __('messages.entries') }})",
                    "lengthMenu": "{{ __('messages.show') }} _MENU_ {{ __('messages.entries') }}",
                    "paginate": {
                        "first": "«",
                        "last": "»",
                        "next": "›",
                        "previous": "‹"
                    },
                    "search": "{{ __('messages.search') }}:",
                    "emptyTable": "{{ __('messages.emptyTable') }}",
                    "zeroRecords": "{{ __('messages.zeroRecords') }}"
                }
            });
            table.on('draw.dt', function() {
                var info = table.page.info();
                table.column(0, {
                    search: 'applied',
                    order: 'applied',
                    page: 'applied'
                }).nodes().each(function(cell, i) {
                    cell.innerHTML = i + 1 + info.start;
                });
            });
        });
    </script>
    <script type="text/javascript">
        $("document").ready(function(){
            setTimeout(function(){
                $("div.alert").remove();
            }, 2000 ); // 2 secs

        });
    </script>
@endsection