routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', function () {
    return redirect('/admin');
});

Route::group(['prefix' => 'admin'], function () {
    App::setLocale('vi');
    Auth::routes();
});

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin', 'name' => 'admin.'],
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');


        //user
        Route::get('user/data', 'UserController@data')->name('user.data');
        Route::resource('user', 'UserController');
        //category
        Route::get('category/data', 'CategoryController@data')->name('category.data');
        Route::resource('category', 'CategoryController');
        //product
        Route::get('product/data', 'ProductController@data')->name('product.data');
        Route::resource('product', 'ProductController');
        //post
        Route::get('post/data', 'PostController@data')->name('post.data');
        Route::resource('post', 'PostController');
    });

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $collection = 'products';

    protected $fillable = ['name','slug','description','quantity','category_id','avatar','image_id'];

    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:m:s',
        'updated_at' => 'datetime:Y-m-d H:m:s',
    ];
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    public function data(Request $request)
    {
        if (empty($request->input('start'))) {
            $request->request->add([
                'start' => '0'
            ]);
        }
        if (empty($request->input('length')) || $request->input('length') === '-1') {
            $request->request->add([
                'length' => Product::all()->count()
            ]);
        }
        if (empty($request->input('search.value'))) {
            $request->request->add([
                'search' => [
                    'value' => '',
                    'regex' => 'false'
                ]
            ]);
        }
        $query = DB::table('products')->leftJoin('categories','products.category_id','=','categories.id')
                ->select('products.*','categories.name as cate_id');
        if ($request->input('search.value')) {
            $query->where('products.name', 'like', '%' . $request->input('search.value') . '%');
        }
        $data = $query->orderBy($request->input('columns.' . $request->input('order.0.column') . '.data') ? $request->input('columns.' . $request->input('order.0.column') . '.data') : 'id', $request->input('order.0.dir') === 'asc' ? 'asc' : 'desc')
            ->skip(intval($request->input('start')))
            ->take(intval($request->input('length')))
            ->get()
            ->toArray();
        $result = [
            'draw' => intval($request->input('draw', 1)),
            'recordsTotal' => intval(Product::all()->count()),
            'recordsFiltered' => intval($query->count()),
            'data' => empty($data) ? [] : $data
        ];
        die(json_encode($result));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Admin.Product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = DB::table('categories')->select('id','name')->get();
        return view('Admin.Product.create',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Product $product)
    {
        $request->validate([
           'name'       => 'required|max:191',
           'description'=> 'required',
           'quantity'  => 'required',
           'category_id'=>'required',
        ]);
        $product = new Product();
        $product->name          = $request->name;
        $product->slug          = str_slug($request->name);
        $product->description   = $request->description;
        $product->quantity      = $request->quantity;
        $product->category_id   = $request->category_id;
        $product->price         = $request->price;
        if($request->avatar){
            $product->name_avatar     = $request->avatar;
            $product->path_avatar     = 'assets/uploads/' . $request->avatar;
        }
        $product->save();
        if($request->hasFile('gallery')){
            foreach ($request->file('gallery') as $image){
                $name = $image->getClientOriginalName();
                $image->move(public_path().'/assets/uploads/gallerys/',$name);
                $img = new Image();
                    $img->name          = $name;
                    $img->description   = $name;
                    $img->cover_img     = '/assets/uploads/gallerys/'.$name;
                    $img->created_at    = Carbon::now();
                $img->save();
                $gallery = DB::table('gallerys')->insert([
                    'product_id'=>$product->id,
                    'image_id'=>$img->id,
                    'created_at'=>Carbon::now(),
                ]);
            }
        }

        return redirect()->route('product.index')->with('message', __('messages.product').' '.__('messages.created').' '.__('messages.successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product,Request $request)
    {
        $category = DB::table('categories')->select('categories.*')->get();
        $gallery = DB::table('gallerys')
            ->leftJoin('products','gallerys.product_id','=','products.id')
            ->leftJoin('images','gallerys.image_id','=','images.id')
            ->where('gallerys.product_id','=',$product->id)
            ->select('cover_img')->get();
        return view('Admin.Product.edit',compact('category','product','gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name'       => 'required|max:191',
            'description'=> 'required',
            'quantity'  => 'required',
            'category_id'=>'required',
        ]);
        $product->name          = $request->name;
        $product->slug          = str_slug($request->name);
        $product->description   = $request->description;
        $product->quantity      = $request->quantity;
        $product->category_id   = $request->category_id;
        $product->price         = $request->price;
        if($request->avatar){
            $product->name_avatar     = $request->avatar;
            $product->path_avatar     = 'assets/uploads/' . $request->avatar;
        }
        if ($request->has('delete_avatar'))
        {
                unlink(public_path($product->path_avatar));
                $product->name_avatar = null;
                $product->path_avatar = null;
        }
        if ($request->has('delete_gallery'))
        {
            DB::table('images')
                ->leftJoin('gallerys','gallerys.image_id','=','images.id')
                ->leftJoin('products','gallerys.product_id','=','products.id')
                ->where('gallerys.product_id','=',$product->id)
                ->delete();
            DB::table('gallerys')
                ->leftJoin('products','gallerys.product_id','=','products.id')
                ->leftJoin('images','gallerys.image_id','=','images.id')
                ->where('gallerys.product_id','=',$product->id)
                ->delete();
        }
        $product->update();
        if($request->hasFile('gallery')){

            foreach ($request->file('gallery') as $image){
                $name = $image->getClientOriginalName();
                $image->move(public_path().'/assets/uploads/gallerys/',$name);
                $img = new Image();
                $img->name          = $name;
                $img->description   = $name;
                $img->cover_img     = '/assets/uploads/gallerys/'.$name;
                $img->created_at    = Carbon::now();
                $img->save();
                DB::table('gallerys')->insert([
                    'product_id'=>$product->id,
                    'image_id'=>$img->id,
                    'created_at'=>Carbon::now(),
                ]);
            }
        }
        return redirect()->route('product.index')->with('message', __('messages.product').' '.__('messages.updated').' '.__('messages.successfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        DB::table('gallerys')->where('product_id',$product->id)->delete();
        return redirect()->route('product.index')->with('message',__('messages.product').' '.__('messages.created').' '.__('messages.successfully'));
    }
}

resources/views/Admin/Product/create.blade.php
@extends('layouts.backend')
@section('content')
<style type="text/css">
    img {
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        width: 100%;
    }
    img:hover {
        box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
    }
    .fancybox-slide--iframe .fancybox-content {
        width  : 800px;
        height : 600px;
        max-width  : 80%;
        max-height : 80%;
        margin: 0;
    }
</style>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/css/fileinput.css" media="all"
      rel="stylesheet" type="text/css">
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" media="all"
      rel="stylesheet" type="text/css">

<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.product') }}</h1>
    </div>
    <!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
            <li class="breadcrumb-item active">{{ __('messages.product') }} </li>
        </ol>
    </div>
</div>
@if ($errors->any())
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h5><i class="icon fas fa-ban"></i>
        @foreach ($errors->all() as $error)
        {{ $error }}
        @endforeach
    </h5>
</div>
@endif
<form method="post" action="{{ route('product.store') }}" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-8">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.add_new') }} {{ __('messages.product') }}</h3>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="name">{{ __('messages.product_name') }}</label>
                        <abbr title="required">*</abbr>
                        <input type="text" class="form-control" id="name" name="name" onkeyup="ChangeToSlug();" placeholder="{{ __('messages.cate_name') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="description">{{ __('messages.description') }}</label>
                        <abbr title="required">*</abbr>
                        <textarea type="text" class="form-control" name="description" id="description" placeholder="{{ __('messages.description') }}"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="gallerys">{{ __('messages.gallerys') }}</label>
                        <input type="file" id="file-1" name="gallery[]" multiple class="file" data-overwrite-initial="false">
                    </div>
                </div>
                <div class="card-footer text-center">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> {{ __('messages.save') }}</button>
                    <button type="reset" class="btn btn-success"><i class="fas fa-redo-alt"></i> {{ __('messages.reset') }}</button>
                    <button type="button" class="btn btn-danger" onclick="javascript:window.location='{{ route('product.index') }}';"><i class="fas fa-sign-out-alt"></i> {{ __('messages.cancel') }}</button>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.static_path') }}</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <label>{{ __('messages.slug') }}</label>
                        <input type="text" class="form-control" id="slug" name="slug" placeholder="{{ __('messages.slug') }}" disabled="">
                    </div>
                </div>
            </div>
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.detail') }}</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="quantity">{{ __('messages.category') }}</label>
                            <abbr title="required">*</abbr>
                            <select class="form-control" id="category_id" name="category_id">
                                @foreach($category as $item)
                                    <option value="{{$item->id }}">{{$item->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="quantity">{{ __('messages.quantity') }}</label>
                            <abbr title="required">*</abbr>
                            <input type="text" class="form-control" name="quantity" id="quantity" placeholder="{{ __('messages.quantity') }}" required>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <label for="price">{{ __('messages.price') }}</label>
                            <abbr title="required">*</abbr>
                            <input type="text" class="form-control"  id="price" name="price" placeholder="{{ __('messages.price') }}">
                        </div>
                        <div class="col-md-3">
                            <label for="price">{{ __('messages.unit') }}</label>
                            <input type="text" class="form-control" placeholder="{{ __('VNĐ') }}" readonly >
                        </div>
                    </div>
                </div>
            </div>
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.avatar') }}</h3>
                </div>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
                <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
                <div class="card-body">
                    <div class="row">
                        <label for="avatar">{{ __('messages.avatar') }}</label>
                        <div class="input-group">
                            <input type="text" name="avatar" id="image-input" class="form-control" readonly>
                            <span class="input-group-append">
                                    <button href="{{ asset('/assets/filemanager/dialog.php?relative_url=1&type=1&field_id=image-input') }}"
                                            name="img_path"  type="button" id="avatar" class="btn  btn-primary iframe-btn" >{{ __('messages.upload_avatar') }}</button>
                                </span>
                        </div>
                    </div><br>
                    <div class="row">
                        <img id="avatar_img" class="image-preview" onClick="swipe();"  width="100%" height="50%" border="1px">
                    </div>
                </div>
            </div>
            <div class="card card-light">

            </div>
        </div>
    </div>
</form>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/js/fileinput.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/themes/fa/theme.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.3/umd/popper.min.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" type="text/javascript"></script>
{{--select multi image input type file--}}
<script type="text/javascript">
    $("#file-1").fileinput({
        theme: 'fa',
        showUpload:false,
        showCancel:false,
        allowedFileExtensions:['jpeg','png','jpg','gif','svg'],
        overwriteInitial:false,
        maxFileSize:2048,
        maxFileNum:5,
        slugCallback:function (filename){
            return filename.replace('(','_').replace(']','_');
        }
    });
</script>
{{--config input type text allow only numberic--}}
<script type="text/javascript">
    function setInputFilter(textbox, inputFilter) {
        ["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function(event) {
            textbox.addEventListener(event, function() {
                if (inputFilter(this.value)) {
                    this.oldValue = this.value;
                    this.oldSelectionStart = this.selectionStart;
                    this.oldSelectionEnd = this.selectionEnd;
                } else if (this.hasOwnProperty("oldValue")) {
                    this.value = this.oldValue;
                    this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
                } else {
                    this.value = "";
                }
            });
        });
    }
    setInputFilter(document.getElementById("quantity"), function(value) { return /^-?\d*$/.test(value); });
    setInputFilter(document.getElementById("price"), function(value) { return /^-?\d*$/.test(value); });

</script>
<script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $('#avatar_img').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#avatar").change(function() {
        readURL(this);
    });
</script>
{{--config select 2--}}
<script type="text/javascript">
    $("#category_id").select2({placeholder: '{{ __('messages.select3') }}', minimumInputLength: 2, theme: 'bootstrap4',});
</script>
{{--config select avatar--}}
<script type="text/javascript">
    $('.iframe-btn').fancybox({
        'type'		: 'iframe',
        'autoScale'    	: false,

    });
    function swipe() {
        var largeImage = document.getElementById('avatar_img');
        var url=largeImage.getAttribute('src');
        window.open(url,'Image','width=largeImage.stylewidth,height=largeImage.style.height,resizable=1');
    }
    function responsive_filemanager_callback(field_id){
        console.log(field_id);
        var url=jQuery('#'+field_id).val();
        $('.image-preview').attr('src','{{ asset('/assets/uploads/') }}' +'/'+ url);
    }
</script>
@endsection

resources/views/Admin/Product/index.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.product') }}</h1>
        </div>
        <!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('messages.product') }} </li>
            </ol>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
    </div>
    <div class="row">
        <div class="col-12">
            @if (session()->has('message'))
                <div class="alert alert-success" id="alert">
                    {{ session()->get('message') }}
                </div>
        @endif
        <!-- /.card -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.product') }}</h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a href="{{ route('product.create') }}" class="btn bg-gradient-info btn-sm">
                                    <i class="fas fa-plus"></i>&nbsp;{{ __('messages.add_new') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <table id="table" class="table table-bordered table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('messages.no.') }}</th>
                            <th>{{ __('messages.product_name') }}</th>
                            <th>{{ __('messages.category') }}</th>
                            <th>{{ __('messages.quantity') }}</th>
                            <th>{{ __('messages.avatar') }}</th>
                            <th>{{ __('messages.created_at') }}</th>
                            <th>{{ __('messages.view') }}</th>
                            <th>{{ __('messages.edit') }}</th>
                            <th>{{ __('messages.delete') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- page script -->
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{{ route('product.data') }}",
                "columns": [{
                    "data": null
                },
                    {
                        "data": "name",
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("product.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '">' + data + '</a>';
                        }
                    },
                    {
                        "data": "cate_id",
                        "render": function(data, type, row, meta) {
                            return data;
                        }
                    },
                    {
                        "data": "quantity",
                        "render": function(data, type, row, meta) {
                            return data;
                        }
                    },
                    {
                        "data": "path_avatar",
                        "render": function(data, type, row, meta) {
                            if(data == null){
                                return '<em>{{ __('messages.avatar_null') }}</em>';
                            }
                            else {
                                return '<img class="border border-secondary" src="{{ asset('/') }}' + data +'" width="45" height="30">';
                            }

                        }
                    },
                    {
                        "data": "created_at",
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("product.show",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '" title="{{ __('messages.view') }}"><img src="{{ asset('img/view.svg') }}" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("product.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '" title="{{ __('messages.edit') }}"><img src="{{ asset('img/edit.svg') }}" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("product.destroy",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<form action="' + url + '" method="post">@csrf @method('DELETE')<button type="submit" class="btn p-0 border-0 bg-transparent" onclick="return confirm(' + "'{{ __('messages.delete_confirmation') }}'" + ')" title="{{ __('messages.delete') }}"><img src="{{ asset('img/delete.svg') }}" width="30" height="30"></button></form>';
                        }
                    }
                ],
                "lengthMenu": [
                    [10, 25, 50, 100, -1],
                    [10, 25, 50, 100, "{{ __('messages.all') }}"]
                ],
                "pagingType": "full_numbers",
                "responsive": {
                    "details": false
                },
                "columnDefs": [{
                    "orderable": false,
                    "targets": [0,3,4,5,6,7,8]
                },
                    {
                        "responsivePriority": 1,
                        "targets": [1,2,3,7,8]
                    },
                    {
                        "className": "text-center",
                        "targets": [0,4,5,6,7,8]
                    }
                ],
                "order": [
                    [1, 'asc']
                ],
                "language": {
                    "processing": "{{ __('messages.processing') }}...",
                    "info": "{{ __('messages.showing') }} _START_ {{ __('messages.to') }} _END_ {{ __('messages.of') }} _TOTAL_ {{ __('messages.entries') }}",
                    "infoEmpty": "{{ __('messages.infoEmpty') }}",
                    "infoFiltered": "({{ __('messages.filtered') }} {{ __('messages.from') }} _MAX_ {{ __('messages.total') }} {{ __('messages.entries') }})",
                    "lengthMenu": "{{ __('messages.show') }} _MENU_ {{ __('messages.entries') }}",
                    "paginate": {
                        "first": "«",
                        "last": "»",
                        "next": "›",
                        "previous": "‹"
                    },
                    "search": "{{ __('messages.search') }}:",
                    "emptyTable": "{{ __('messages.emptyTable') }}",
                    "zeroRecords": "{{ __('messages.zeroRecords') }}"
                }
            });
            table.on('draw.dt', function() {
                var info = table.page.info();
                table.column(0, {
                    search: 'applied',
                    order: 'applied',
                    page: 'applied'
                }).nodes().each(function(cell, i) {
                    cell.innerHTML = i + 1 + info.start;
                });
            });
        });
    </script>
    <script type="text/javascript">
        $("document").ready(function(){
            setTimeout(function(){
                $("div.alert").remove();
            }, 2000 ); // 2 secs

        });
    </script>
@endsection