routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

Route::get('/home', function () {
    return redirect('/admin');
});

Route::group(['prefix' => 'admin'], function () {
    App::setLocale('vi');
    Auth::routes();
});

Route::group(['middleware' => ['auth'], 'namespace' => 'Admin', 'prefix' => 'admin', 'name' => 'admin.'],
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');


        //user
        Route::get('user/data', 'UserController@data')->name('user.data');
        Route::resource('user', 'UserController');
        //category
        Route::get('category/data', 'CategoryController@data')->name('category.data');
        Route::resource('category', 'CategoryController');
        //product
        Route::get('product/data', 'ProductController@data')->name('product.data');
        Route::resource('product', 'ProductController');
        //post
        Route::get('post/data', 'PostController@data')->name('post.data');
        Route::resource('post', 'PostController');
    });

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;


use App\Models\Category;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function data(Request $request)
    {
        if (empty($request->input('start'))) {
            $request->request->add([
                'start' => '0'
            ]);
        }
        if (empty($request->input('length')) || $request->input('length') === '-1') {
            $request->request->add([
                'length' => Category::all()->count()
            ]);
        }
        if (empty($request->input('search.value'))) {
            $request->request->add([
                'search' => [
                    'value' => '',
                    'regex' => 'false'
                ]
            ]);
        }
        $query = User::query();
        if ($request->input('search.value')) {
            $query->where('name', 'like', '%' . $request->input('search.value') . '%')
            ->orwhere('email', 'like', '%' . $request->input('search.value') . '%');
        }
        $data = $query->orderBy($request->input('columns.' . $request->input('order.0.column') . '.data') ? $request->input('columns.' . $request->input('order.0.column') . '.data') : 'id', $request->input('order.0.dir') === 'asc' ? 'asc' : 'desc')
            ->skip(intval($request->input('start')))
            ->take(intval($request->input('length')))
            ->get()
            ->toArray();
        $result = [
            'draw' => intval($request->input('draw', 1)),
            'recordsTotal' => intval(User::all()->count()),
            'recordsFiltered' => intval($query->count()),
            'data' => empty($data) ? [] : $data
        ];
        die(json_encode($result));
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Admin.User.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        DB::table('user')->delete();
    }
}

resources/views/Admin/User/create.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.category') }}</h1>
        </div>
        <!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('messages.category') }} </li>
            </ol>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
    </div>
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i>
                @foreach ($errors->all() as $error)
                   {{ $error }}
                @endforeach
            </h5>
        </div>
    @endif
    <div class="row">
        <!-- left column -->
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.add_new') }} {{ __('messages.category') }}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post" action="{{ route('category.store') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">{{ __('messages.cate_name') }}</label>
                            <input type="text" class="form-control" id="name" name="name" onkeyup="ChangeToSlug();" placeholder="{{ __('messages.cate_name') }}">
                        </div>
                        <div class="form-group">
                            <label for="description">{{ __('messages.description') }}</label>
                            <textarea type="text" class="form-control" name="description" id="description" placeholder="{{ __('messages.description') }}"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="type">{{ __('messages.type') }}</label><br>
                            @foreach($type as $item)
                                <input type="radio" id="type" name="type" value="{{$item->id}}">
                                <label for="type">{{$item->name}}</label>&#160;&#160;&#160;&#160;
                            @endforeach
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                        <button type="reset" class="btn btn-success"><i class="fas fa-redo-alt"></i> Reset</button>
                        <button type="button" class="btn btn-danger" onclick="javascript:window.location='{{ route('category.index') }}';"><i class="fas fa-sign-out-alt"></i> Cancel</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
        <div class="col-md-4">
            <!-- general form elements disabled -->
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.static_path') }}</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                        <div class="row">
                            <label>{{ __('messages.slug') }}</label>
                            <input type="text" class="form-control" id="slug" name="slug" placeholder="Enter ..." disabled="" >
                        </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
        <!--/.col (right) -->
    </div>
@endsection

resources/views/Admin/User/edit.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ __('messages.edit') }} {{ __('messages.category') }}</h1>
        </div>
        <!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('messages.category') }} </li>
            </ol>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
    </div>
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i>
                @foreach ($errors->all() as $error)
                    {{ $error }}
                @endforeach
            </h5>
        </div>
    @endif
    <div class="row">
        <!-- left column -->
        <div class="col-md-8">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.edit') }} {{ __('messages.category') }}</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="post" action="{{ route('category.update',$category->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">{{ __('messages.cate_name') }}</label>
                            <input type="text" class="form-control" id="name" name="name" onkeyup="ChangeToSlug();" placeholder="{{ __('messages.cate_name') }}" value={{$category->name}}>
                        </div>
                        <div class="form-group">
                            <label for="description">{{ __('messages.description') }}</label>
                            <textarea type="text" class="form-control" name="description" id="description" placeholder="{{ __('messages.description') }}">{{$category->description}}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="type">{{ __('messages.type') }}</label><br>
                            @foreach($type as $item)
                                <input type="radio" id="type" name="type" value="{{$item->id}}" @if($category->type == $item->id) checked @endif>
                                <label for="type">{{$item->name}}</label>&#160;&#160;&#160;&#160;
                            @endforeach
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Save</button>
                        <button type="reset" class="btn btn-success"><i class="fas fa-redo-alt"></i> Reset</button>
                        <button type="button" class="btn btn-danger" onclick="javascript:window.location='{{ route('category.index') }}';"><i class="fas fa-sign-out-alt"></i> Cancel</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
        <div class="col-md-4">
            <!-- general form elements disabled -->
            <div class="card card-light">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.static_path') }}</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <label>{{ __('messages.slug') }}</label>
                        <input type="text" class="form-control" id="slug" name="slug" value="{{ $category->slug }}" placeholder="Enter ..." disabled="" >
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
        <!--/.col (right) -->
    </div>
@endsection

resources/views/Admin/User/index.blade.php
@extends('layouts.backend')
@section('content')
    <div class="row mb-2">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ __('messages.list') }} {{ __('messages.user') }}</h1>
        </div>
        <!-- /.col -->
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">{{ __('messages.home') }}</a></li>
                <li class="breadcrumb-item active">{{ __('messages.user') }} </li>
            </ol>
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    </div><!-- /.container-fluid -->
    </div>
    <div class="row">
        <div class="col-12">
            @if (session()->has('message'))
                <div class="alert alert-success" id="alert">
                    {{ session()->get('message') }}
                </div>
            @endif
            <!-- /.card -->
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ __('messages.user') }}</h3>
                    <div class="card-tools">
                        <ul class="nav nav-pills">
                            <li class="nav-item">
                                <a href="{{ route('category.create') }}" class="btn bg-gradient-info btn-sm">
                                    <i class="fas fa-plus"></i>&nbsp;{{ __('messages.add_new') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="card-body">
                    <table id="table" class="table table-bordered table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{{ __('messages.no.') }}</th>
                            <th>{{ __('messages.name') }}</th>
                            <th>{{ __('messages.email') }}</th>
                            <th>{{ __('messages.edit') }}</th>
                            <th>{{ __('messages.delete') }}</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- page script -->
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "{{ route('user.data') }}",
                "columns": [{
                    "data": null
                },
                    {
                        "data": "name",
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("user.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '">' + data + '</a>';
                        }
                    },
                    {
                        "data": "email",
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("user.edit",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<a href="' + url + '" title="{{ __('messages.edit') }}"><img src="{{ asset('img/edit.svg') }}" width="30" height="30"></a>';
                        }
                    },
                    {
                        "data": null,
                        "render": function(data, type, row, meta) {
                            var url = '{{ route("user.destroy",":id") }}';
                            url = url.replace(':id', row.id);
                            return '<form action="' + url + '" method="post">@csrf @method('DELETE')<button type="submit" class="btn p-0 border-0 bg-transparent" onclick="return confirm(' + "'{{ __('messages.delete_confirmation') }}'" + ')" title="{{ __('messages.delete') }}"><img src="{{ asset('img/delete.svg') }}" width="30" height="30"></button></form>';
                        }
                    }
                ],
                "lengthMenu": [
                    [10, 25, 50, 100, -1],
                    [10, 25, 50, 100, "{{ __('messages.all') }}"]
                ],
                "pagingType": "full_numbers",
                "responsive": {
                    "details": false
                },
                "columnDefs": [{
                    "orderable": false,
                    "targets": [0,3,4]
                },
                    {
                        "responsivePriority": 1,
                        "targets": [1,2,4]
                    },
                    {
                        "className": "text-center",
                        "targets": [0,3,4]
                    }
                ],
                "order": [
                    [1, 'asc']
                ],
                "language": {
                    "processing": "{{ __('messages.processing') }}...",
                    "info": "{{ __('messages.showing') }} _START_ {{ __('messages.to') }} _END_ {{ __('messages.of') }} _TOTAL_ {{ __('messages.entries') }}",
                    "infoEmpty": "{{ __('messages.infoEmpty') }}",
                    "infoFiltered": "({{ __('messages.filtered') }} {{ __('messages.from') }} _MAX_ {{ __('messages.total') }} {{ __('messages.entries') }})",
                    "lengthMenu": "{{ __('messages.show') }} _MENU_ {{ __('messages.entries') }}",
                    "paginate": {
                        "first": "«",
                        "last": "»",
                        "next": "›",
                        "previous": "‹"
                    },
                    "search": "{{ __('messages.search') }}:",
                    "emptyTable": "{{ __('messages.emptyTable') }}",
                    "zeroRecords": "{{ __('messages.zeroRecords') }}"
                }
            });
            table.on('draw.dt', function() {
                var info = table.page.info();
                table.column(0, {
                    search: 'applied',
                    order: 'applied',
                    page: 'applied'
                }).nodes().each(function(cell, i) {
                    cell.innerHTML = i + 1 + info.start;
                });
            });
        });
    </script>
@endsection